//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvilWords {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Wordlist {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Wordlist() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EvilWords.Wordlist", typeof(Wordlist).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aahed
        ///aalii
        ///aargh
        ///aarti
        ///abaca
        ///abaci
        ///abacs
        ///abaft
        ///abaka
        ///abamp
        ///aband
        ///abash
        ///abask
        ///abaya
        ///abbas
        ///abbed
        ///abbes
        ///abcee
        ///abeam
        ///abear
        ///abele
        ///abers
        ///abets
        ///abies
        ///abler
        ///ables
        ///ablet
        ///ablow
        ///abmho
        ///abohm
        ///aboil
        ///aboma
        ///aboon
        ///abord
        ///abore
        ///abram
        ///abray
        ///abrim
        ///abrin
        ///abris
        ///absey
        ///absit
        ///abuna
        ///abune
        ///abuts
        ///abuzz
        ///abyes
        ///abysm
        ///acais
        ///acari
        ///accas
        ///accoy
        ///acerb
        ///acers
        ///aceta
        ///achar
        ///ached
        ///aches
        ///achoo
        ///acids
        ///acidy
        ///acing
        ///acini
        ///ackee
        ///acker
        ///acmes
        ///acmic
        ///acned
        ///acnes
        ///acock
        ///acold
        ///acred
        ///acres
        ///a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FiveLetterGuessWords {
            get {
                return ResourceManager.GetString("FiveLetterGuessWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cigar
        ///rebut
        ///sissy
        ///humph
        ///awake
        ///blush
        ///focal
        ///evade
        ///naval
        ///serve
        ///heath
        ///dwarf
        ///model
        ///karma
        ///stink
        ///grade
        ///quiet
        ///bench
        ///abate
        ///feign
        ///major
        ///death
        ///fresh
        ///crust
        ///stool
        ///colon
        ///abase
        ///marry
        ///react
        ///batty
        ///pride
        ///floss
        ///helix
        ///croak
        ///staff
        ///paper
        ///unfed
        ///whelp
        ///trawl
        ///outdo
        ///adobe
        ///crazy
        ///sower
        ///repay
        ///digit
        ///crate
        ///cluck
        ///spike
        ///mimic
        ///pound
        ///maxim
        ///linen
        ///unmet
        ///flesh
        ///booby
        ///forth
        ///first
        ///stand
        ///belly
        ///ivory
        ///seedy
        ///print
        ///yearn
        ///drain
        ///bribe
        ///stout
        ///panel
        ///crass
        ///flume
        ///offal
        ///agree
        ///error
        ///swirl
        ///a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FiveLetterSolutionWords {
            get {
                return ResourceManager.GetString("FiveLetterSolutionWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honey
        ///Taunt
        ///Devil
        ///Demon
        ///Loser
        ///Dummy
        ///Nasty
        ///Trick
        ///Scorn
        ///Sneer
        ///Scoff
        ///Laugh
        ///Moron
        ///Clown
        ///Dunce
        ///Twerp
        ///Cheat
        ///Bluff
        ///Wrong
        ///Curse
        ///Awful
        ///Venom
        ///Taint
        ///Moist.
        /// </summary>
        internal static string FiveLetterTaunts {
            get {
                return ResourceManager.GetString("FiveLetterTaunts", resourceCulture);
            }
        }
    }
}
